<?php

namespace EventBundle\Repository;

/**
 * EventUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventUserRepository extends \Doctrine\ORM\EntityRepository
{
}
