<?php

namespace OrchardBundle\Repository;

/**
 * InscriptionStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionStepRepository extends \Doctrine\ORM\EntityRepository
{
}
