<?php

namespace OrchardBundle\Repository;

/**
 * OrchardParticipateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrchardParticipateRepository extends \Doctrine\ORM\EntityRepository
{
}
