<?php

namespace OrchardBundle\Repository;

/**
 * OrchardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrchardRepository extends \Doctrine\ORM\EntityRepository
{
}
