<?php

namespace OrchardBundle\Repository;

/**
 * OrchardServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrchardServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
