<?php

namespace OrchardBundle\Repository;

/**
 * OrchardActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrchardActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
