<?php

namespace OrchardBundle\Repository;

/**
 * OrchardTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrchardTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
