<?php

namespace OrchardBundle\Repository;

/**
 * RuleFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleFileRepository extends \Doctrine\ORM\EntityRepository
{
}
